#pragma config(Sensor, S1,     Sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     Colour,         sensorEV3_Color)
#pragma config(Motor,  motorA,          Left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          Lift,          tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Moves forward x seconds
void moveForward (int x) {
	motor[Left] = 30;
	motor[Right] = 30;
	wait1Msec(x * 1000);
}

//Turns right approx x degrees
//Did some tests and x*9 gave us the approximate correct angle
void turnRight(int x) {
	motor[Left] = 20;
	motor[Right] = -20;
	wait1Msec(x*9);
}

//turns left approx x degrees
void turnLeft(int x) {
	motor[Left] = -20;
	motor[Right] = 20;
	wait1Msec(x*9);
}

void WalledRoom() {

}

void FireRoom() {

}

void SurviorRoom() {

}

void EmptyRoom() {

}


task main(){
	//---------------------------------------------------Stage 1-----------------------------------------------------
	int WallDistance = 20;
	int i = 0;

	while(i<4){
		if(SensorValue[Sonar]	< WallDistance){
			WalledRoom();
		}
		else{
			//Move Forward Slightly to get ready to check for survivor
			moveForward(2);
			//Use Encoders here to turn to around 130 degrees
			while(Angle < 130){ //Rotate Clockwise
				int LowestDistance = 30000;
				while(SensorValue(Sonar)>LowestDistance){
					motor[Left] = -10;
					motor[Right] = 10;

					if(SensorValue(Sonar) < LowestDistance){
						LowestDistance = SensorValue(Sonar);
					}
				}

				//SurvivorDistance is the distance we would expect the survivor to be at
				int SurvivorDistance = 10;
				//If the distance is closer than we would expect in a clear room, we must have picked up the survivor with the sonar
				if(LowestDistance<SurvivorDistance){
					while(SensorValue(Sonar)>LowestDistance){
						motor[Left] = 10;
						motor[Right] = -10;
					}
					SurviorRoom();
				}

				else{
					clearTimer(T1);
					bool isFireRoom = false;

					while(time1[T1] < 3000){
						motor[Left] = 20;
						motor[Right] = 20;

						if(SensorValue(Colour) == 5){
							isFireRoom = true;
							break;
						}
					}

					if(isFireRoom == true) {
						FireRoom();
					}
					else{
						EmptyRoom();
					}
				}
			}
			i++;
		}
	}
}
