#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Colour,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_Angle)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//C=left B=right

//Moves forward x*100 amount of milliseconds
void moveForward (int x) {
 	 	motor[motorB] = 30;
 		motor[motorC] = 30;
 		wait1Msec(x * 100);
}

//Turns right x degrees
void turnRight(int x) {
 	 	motor[motorC] = 20;
 		motor[motorB] = -20;
 		wait1Msec(x*10);
}

//turns left x degrees
void turnLeft(int x) {
 	 	motor[motorC] = -20;
 		motor[motorB] = 20;
 		wait1Msec(x*10);
}

task main()

//---------------------------------------------------Stage 1-------------------------------------------------------
{
	//Goes Forward until input recieved from touch sensor.
	while(SensorValue(Touch) == 0)
 	{
 		motor[motorC] = 40;
 		motor[motorB] = 40;
 	}

 	motor[motorC] = 0;
 	motor[motorB] = 0;
	wait1Msec(50);


 	while(SensorValue(Sonar) < 34)
 	{
 		motor[motorC] = -20;
 		motor[motorB] = -20;
 	}

 	turnLeft(90);

	moveForward(2);

	while(SensorValue[Colour] != 5){
		motor[motorC] = 20;
		motor[motorB] = 10;
	}

 	clearTimer(T1);

//---------------------------------------------------Stage 2-------------------------------------------------------

 	//Follows line
 	while(time1[T1] < 14000)//chang end condition
 	{
 		if(SensorValue[Colour] == 5)
 		{
 			motor[motorC] = 0;
 			motor[motorB] = 30;
 		}
 		else
 		{
 			motor[motorC] = 30;
 			motor[motorB] = 0;
 		}
 	}

 //Will stop line tracking once close enough to the wall

 while(SensorValue(Sonar) > 30)//chang end condition
 	{
 		if(SensorValue[Colour] == 5)
 		{
 			motor[motorC] = 20;
 			motor[motorB] = 30;
 		}
 		else
 		{
 			motor[motorC] = 30;
 			motor[motorB] = 20;
 		}
 	}

//---------------------------------------------------Stage 3-------------------------------------------------------

 	//Move forward until within 6cm of the wall
 	 while(SensorValue(Sonar) > 6) {
 		motor[motorC] = 30;
 		motor[motorB] = 30;
 	}

 	while(SensorValue(Gyro)% 360 != 270) {
 		motor[motorB] = 20;
 		motor[motorC] = -20;
 	}


}
